import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h4>menu</h4>
      </div>
      <div>
        <h1>hello word</h1>
      </div>
      <div>
        <h4>footer</h4>
      </div>
    </>
  );
};

export default Home;
